src/account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

src/gts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("account.urls")),
    path('', include("panel.urls")),
]

src/panel/urls.py
from django.urls import path
from django.conf.urls import handler404, handler403

from . import views

app_name = "panel"

urlpatterns = [
    path('', views.panel_home_view, name='home'),
    path('theses/all/', views.panel_home_view, name='all_theses'),
    path('theses/my/', views.panel_my_theses_view, name='my_theses'),
    path('theses/<int:thesis_id>', views.panel_thesis_detail_view, name="thesis_detail"),
    path('theses/new/', views.panel_new_thesis_view, name="new_thesis"),
    path('theses/<int:thesis_id>/edit/', views.panel_edit_thesis_view, name="edit_thesis"),
    
    path('universities/all/', views.panel_all_universities_view, name='all_universities'),
    path('universities/<int:university_id>', views.panel_university_detail_view, name='university_detail'),
    path('universities/new/', views.panel_new_university_view, name='new_university'),
    path('universities/<int:university_id>/edit/', views.panel_edit_university_view, name='edit_university'),
    
    path('institutes/all/', views.panel_all_institutes_view, name='all_institutes'),
    path('institutes/<int:institute_id>', views.panel_institute_detail_view, name='institute_detail'),
    path('institutes/new/', views.panel_new_institute_view, name='new_institute'),
    path('institutes/<int:institute_id>/edit/', views.panel_edit_institute_view, name='edit_institute'),
    
    
    #path('types/all/', views.panel_all_types_view, name='all_types'),
    #path('types/<int:type_id>', views.panel_type_detail_view, name='type_detail'),
    #path('types/new/', views.panel_new_type_view, name='new_type'),
    #path('types/<int:type_id>/edit/', views.panel_edit_type_view, name='edit_type'),
    
    path('languages/all/', views.panel_all_languages_view, name='all_languages'),
    path('languages/<int:language_id>', views.panel_language_detail_view, name='language_detail'),
    path('languages/new/', views.panel_new_language_view, name='new_language'),
    path('languages/<int:language_id>/edit/', views.panel_edit_language_view, name='edit_language'),

]

handler404 = views.panel_404_view

src/panel/models.py
from django.db import models

# Create your models here.

class Thesis(models.Model):
    
    
    title = models.CharField(max_length=500)
    abstract = models.CharField(max_length=5000)
    page_no = models.IntegerField()
    write_date = models.DateField(blank=True, null=True)
    sub_date = models.DateField(auto_now_add=True, blank=True, null=True)
    
    author = models.ForeignKey("account.User", on_delete=models.DO_NOTHING, related_name="author", db_constraint=False)
    supervisor = models.ForeignKey("account.User", on_delete=models.DO_NOTHING, related_name="supervisor", db_constraint=False)
    cosupervisor = models.ForeignKey("account.User", on_delete=models.DO_NOTHING, related_name="cosupervisor", blank=True, null=True, db_constraint=False)
    institute = models.ForeignKey("panel.Institute", on_delete=models.DO_NOTHING, db_constraint=False)
    type = models.ForeignKey("panel.Type", on_delete=models.DO_NOTHING, db_constraint=False)
    language = models.ForeignKey("panel.Language", on_delete=models.DO_NOTHING, db_constraint=False)
    
    subjects = models.ManyToManyField("panel.Subject", blank=True, null=True)
    keywords = models.ManyToManyField("panel.Keyword", blank=True, null=True)
    

class University(models.Model):
    name = models.CharField(max_length=60)
    
    def __str__(self):
        return self.name

class Institute(models.Model):
    name = models.CharField(max_length=100)
    university = models.ForeignKey("panel.University", on_delete=models.DO_NOTHING, db_constraint=False)
    
    def __str__(self):
        return self.university.name + " / " + self.name

class Language(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Type(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
class Subject(models.Model):
    heading = models.CharField(max_length=255)
    
    def __str__(self):
        return self.heading

class Keyword(models.Model):
    description = models.CharField(max_length=50)

src/panel/views.py
import datetime

from django.shortcuts import render, redirect

from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.db.models import Q, Value, F, CharField
from django.db.models.functions import Concat

from account.decorators import allowed_users
from account.models import User

from .models import Thesis, Keyword, Subject, Institute, University, Type, Language

from .forms import NewThesisForm, NewInstituteForm

from .utils import numbering


@login_required(login_url='account:login')
def panel_my_theses_view(request):

    total = 0
    page = 1
    search = None
    write = False
    supervise = False
    cosupervise = False
    query:Q = Q()

    if request.method == 'POST':
        print(request.POST)
        
        if request.POST.get('page'):
            page = int(request.POST.get('page'))
        
        if request.POST.get('search-kwd'):
            search = request.POST.get('search-kwd')
        
        if not request.POST.get('write') and not request.POST.get('supervise') and not request.POST.get('cosupervise'):
            write = True
        
        if request.POST.get('write'):
            write = True
            query = query | Q(author=request.user)
            
        if request.POST.get('supervise'):
            supervise = True
            query = query | Q(supervisor=request.user)
        
        if request.POST.get('cosupervise'):
            cosupervise = True
            query = query | Q(cosupervisor=request.user)
        
        if search:
            print(Thesis.objects.annotate(combined=Concat('title', Value(' '), 'abstract', Value(' '), 'institute__name', Value(' '), 'institute__university__name', output_field=CharField())).filter(Q(author=request.user) & (Q(combined__icontains=search) & query)).order_by('id').query)
            all_theses = Thesis.objects.annotate(combined=Concat('title', Value(' '), 'abstract', Value(' '), 'institute__name', Value(' '), 'institute__university__name', output_field=CharField())).filter(Q(author=request.user) & (Q(combined__icontains=search) & query)).order_by('id')
        else:
            all_theses = Thesis.objects.all().filter(Q(author=request.user) & query).order_by('id')
    else:
        all_theses = Thesis.objects.all().filter(author=request.user).order_by('id')
 

    total = len(all_theses)
    if total > 10:
        all_theses = numbering.paginate(all_theses, page)
    
    context = {
        'all_theses': all_theses,
        'write': write,
        'supervise': supervise,
        'cosupervise': cosupervise,
        'total': total,
        'first': ((page-1)*10)+1,
        'last': ((page-1)*10)+len(all_theses),
        'if_first': ((page-1)*10)+1 == 1,
        'if_last': ((page-1)*10)+len(all_theses) == total,
        'search': search,
        'page': page
    }

    return render(request, "panel/pages/theses/my_theses.html", context)

@login_required(login_url='account:login')
def panel_thesis_detail_view(request, thesis_id):
    try:
        thesis = Thesis.objects.get(id=thesis_id)
    except Thesis.DoesNotExist:
        return redirect("panel:all_theses")
    
    
    if request.method == 'POST':
        if request.POST.get('field') == 'delete':
            thesis.delete()
            return redirect("panel:all_theses")
            
    
    

    context = {
        'thesis': thesis,
        'subjects': ", ".join(map(str, [x.heading for x in thesis.subjects.all()])),
        'keywords': ", ".join(map(str, [x.description for x in thesis.keywords.all()])),
    }

    return render(request, "panel/pages/theses/thesis_detail.html", context)

@login_required(login_url='account:login')
def panel_new_thesis_view(request):
    
    current_user:User = request.user

    if request.method == 'POST':
        print(request.POST)
        form = NewThesisForm(data = request.POST)
        if form.is_valid():
            
            thesis:Thesis = form.save(commit=False)
            
            error:bool = False
            
            try:
                thesis.supervisor = User.objects.get(username=request.POST.get('supervisor'))
            except User.DoesNotExist:
                messages.error(request, "Supervisor couldn't be found.", extra_tags="supervisor")
                error = True
            
            if request.POST.get('cosupervisor'):
                try:
                    thesis.cosupervisor = User.objects.get(username=request.POST.get('cosupervisor'))
                except User.DoesNotExist:
                    messages.error(request, "Cosupervisor couldn't be found.", extra_tags="cosupervisor")
                    error = True
            if error:
                return redirect('panel:new_thesis')
            
            thesis.author = current_user
            thesis.save()
            
            thesis.subjects.add(*[Subject.objects.get(id=s) for s in request.POST.getlist('subjects')])
            
            kwd = request.POST.get('keywords')
            
            if kwd:
                for x in list(map(str.strip, kwd.strip('][').replace('"', '').split(','))):
                    x=x.lower()
                    if Keyword.objects.filter(description=x).exists():
                        thesis.keywords.add(Keyword.objects.get(description=x))
                    else:
                        thesis.keywords.create(description=x)
                    
            
            
            return redirect('panel:thesis_detail', thesis_id=thesis.id)
        else:
            print(form.errors)
    else:
        form = NewThesisForm()
    
    context = { 'new_thesis_form': form,
               'now': str(datetime.datetime.now()),}

    return render(request, "panel/pages/theses/new_thesis.html", context)

@login_required(login_url='account:login')
def panel_edit_thesis_view(request, thesis_id):
    
    current_user:User = request.user
    
    try:
        thesis = Thesis.objects.get(pk=thesis_id)
    except Thesis.DoesNotExist:
        return redirect("panel:all_theses")

    if request.method == 'POST':
        
        
        if request.POST.get('field') == 'delete':
            thesis.delete()
            return redirect("panel:all_theses")
        
        form = NewThesisForm(data = request.POST)
        if form.is_valid():
            form.instance.sub_date = thesis.sub_date
            thesis:Thesis = form.save(commit=False)
            thesis.id = thesis_id
            
            error:bool = False
            
            try:
                thesis.supervisor = User.objects.get(username=request.POST.get('supervisor'))
            except User.DoesNotExist:
                messages.error(request, "Supervisor couldn't be found.", extra_tags="supervisorerror")
                error = True
            
            if request.POST.get('cosupervisor'):
                try:
                    thesis.cosupervisor = User.objects.get(username=request.POST.get('cosupervisor'))
                except User.DoesNotExist:
                    messages.error(request, "Cosupervisor couldn't be found.", extra_tags="cosupervisor")
                    error = True
            else:
                thesis.cosupervisor = None
            
            
            if error:
                return redirect('panel:edit_thesis', thesis_id=thesis_id)
            
            thesis.author = current_user
            thesis.save()
            
            thesis.subjects.clear()
            thesis.subjects.add(*[Subject.objects.get(id=s) for s in request.POST.getlist('subjects')])
            
            thesis.keywords.clear()
            kwd = request.POST.get('keywords')
            
            if kwd:
                for x in list(map(str.strip, kwd.strip('][').replace('"', '').split(','))):
                    x=x.lower()
                    if Keyword.objects.filter(description=x).exists():
                        thesis.keywords.add(Keyword.objects.get(description=x))
                    else:
                        thesis.keywords.create(description=x)
                    
            
            
            return redirect('panel:thesis_detail', thesis_id=thesis.id)
    else:
        form = NewThesisForm(instance=thesis)
        
    
    keywords = ", ".join(map(str, [x.description for x in thesis.keywords.all()]))
    
    context = { 'new_thesis_form': form,
               'supervisor': thesis.supervisor.username,
               'cosupervisor': thesis.cosupervisor.username if thesis.cosupervisor else '',
               'keywords': keywords,
               'thesis_id': thesis_id,}

    return render(request, "panel/pages/theses/edit_thesis.html", context)




@login_required(login_url='account:login')
def panel_all_institutes_view(request):

    total = 0
    page = 1
    search = None

    if request.method == 'POST':
        
        if request.POST.get('page'):
            page = int(request.POST.get('page'))
        
        if request.POST.get('search-kwd'):
            search = request.POST.get('search-kwd')
    
    if search:
        all_institutes = Institute.objects.annotate(combined=Concat('name', Value(' '), 'university__name')).filter(combined__icontains=search).order_by('name')
    else:
        all_institutes = Institute.objects.all().order_by('name')
 

    total = len(all_institutes)
    if total > 10:
        all_institutes = numbering.paginate(all_institutes, page)
    
    context = {
        'all_insts': all_institutes,
        'total': total,
        'first': ((page-1)*10)+1,
        'last': ((page-1)*10)+len(all_institutes),
        'if_first': ((page-1)*10)+1 == 1,
        'if_last': ((page-1)*10)+len(all_institutes) == total,
        'search': search,
        'page': page
    }

    return render(request, "panel/pages/institutes/all_institutes.html", context)

@login_required(login_url='account:login')
def panel_institute_detail_view(request, institute_id):
    try:

src/panel/templates/panel/partials/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="dark">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="GTS - Panel">

    <title>{% block title %}{% endblock %}</title>

    {% include "panel/partials/_stylesheet.html" %}

    {% include "panel/partials/_favicon.html" %}

    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark')
        }
    </script>

    <body class="bg-gray-50 dark:bg-gray-800">
        
        {% include "panel/partials/_navbar.html" %}

        <div class="flex mt-[65px] overflow-hidden bg-gray-50 dark:bg-gray-900">

            {% include "panel/partials/_sidebar.html" %}
            
            <div id="main-content" class="relative w-full h-screen overflow-y-auto bg-gray-50 lg:ml-64 dark:bg-gray-900">
            <main>
                {% block content %}{% endblock %}
            </main>
            
            {% include "panel/partials/_footer.html" %}

            </div>
        
        </div>

        
        
        {% include "panel/partials/_scripts.html" %}
        {{ redirect_to_login_immediately }}

    </body>

</html>

src/panel/templates/panel/partials/_favicon.html
{% load static %}

<!-- FAVICONS -->

<!-- <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"> -->
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'panel/img/favicon32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'panel/img/favicon16.png' %}">
<!-- <link rel="icon" type="image/png" href="/favicon.ico">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"> -->
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

src/panel/templates/panel/partials/_footer.html
<footer class="relative p-4 my-6 mx-4 bottom-0 bg-white rounded-lg shadow md:flex md:items-center md:justify-center md:p-6 xl:p-6 dark:bg-gray-800">
    
    <p class="text-sm text-center text-gray-500">
        &copy; 2024 - <a href="" class="hover:underline" target="_blank">SE307</a>. 
        <br>
        1990711002, 200706019, 210704024, 230704301.
    </p>
    
</footer>

  

src/panel/templates/panel/partials/_navbar.html
{% load static %}

<nav class="fixed z-30 top-0 w-full bg-white border-b border-gray-200 dark:bg-gray-800 dark:border-gray-700">
    <div class="px-3 py-3 lg:px-5 lg:pl-3">
      <div class="flex items-center justify-between">
        <div class="flex items-center justify-start">
  
          <button id="toggleSidebarMobile" aria-expanded="true" aria-controls="sidebar" class="p-2 text-gray-600 rounded cursor-pointer lg:hidden hover:text-gray-900 hover:bg-gray-100 focus:bg-gray-100 dark:focus:bg-gray-700 focus:ring-2 focus:ring-gray-100 dark:focus:ring-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            <svg id="toggleSidebarMobileHamburger" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
            <svg id="toggleSidebarMobileClose" class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </button>
  
          <a href="{% url 'panel:home' %}" class="flex ml-2 md:mr-24">
            {% comment %} <img src="{% static 'panel/img/logo_dark.png' %}" class="h-8 mr-3 dark:block hidden" alt="GTS" />
            <img src="{% static 'panel/img/logo_light.png' %}" class="h-8 mr-3 dark:hidden block" alt="GTS" />
            <span class="self-center text-xl font-semibold sm:text-2xl whitespace-nowrap dark:text-white">|  Graduate Thesis System</span> {% endcomment %}
            <span class="self-center text-xl font-semibold sm:text-2xl whitespace-nowrap dark:text-white">Graduate Thesis System</span>
          </a>
  
          
  
        </div>
  
        <div class="flex items-center">
            
            <!-- Apps -->
            <button type="button" data-dropdown-toggle="apps-dropdown" class="hidden p-2 text-gray-500 rounded-lg sm:flex hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700">
              <span class="sr-only">Bildirimleri gör</span>
              <!-- Icon -->
              <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"></path></svg>
            </button>
            <!-- Dropdown menu -->
            <div class="z-50 hidden max-w-sm my-4 overflow-hidden text-base list-none bg-white divide-y divide-gray-100 rounded shadow-lg dark:bg-gray-700 dark:divide-gray-600" id="apps-dropdown">
              <div class="block px-4 py-2 text-base font-medium text-center text-gray-700 bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                  Uygulamalar
              </div>
              <div class="grid grid-cols-3 gap-4 p-4">
                
                <a href="{% url "account:logout" %}" class="block p-4 text-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600">
                  <svg class="mx-auto mb-1 text-gray-500 w-7 h-7 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"></path></svg>
                    <div class="text-sm font-medium text-gray-900 dark:text-white">Çıkış Yap</div>
                </a>
              </div>
            </div>
            <button id="theme-toggle" data-tooltip-target="tooltip-toggle" type="button" class="text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5">
              <svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path></svg>
              <svg id="theme-toggle-light-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
            </button>
            <div id="tooltip-toggle" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip">
                Change dark/light mode
                <div class="tooltip-arrow" data-popper-arrow></div>
            </div>
            <!-- Profile -->
            <div class="flex items-center ml-3">
              <div>
                <button type="button" class="flex text-sm bg-gray-800 rounded-full focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button-2" aria-expanded="false" data-dropdown-toggle="dropdown-2">
                  <span class="sr-only">User Menu</span>
                  {% if user.profile_pic_path %}
                  <img class="w-8 h-8 rounded-full" src="{{ user.profile_pic_path.url }}" alt="">
                  {% else %}
                  <img class="w-8 h-8 rounded-full" src="{% static 'panel/img/default_pp.png' %}" alt="">
                  {% endif %}
                </button>
              </div>
              <!-- Dropdown menu -->
              <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600" id="dropdown-2">
                <div class="px-4 py-3" role="none">
                  <p class="text-sm text-gray-900 dark:text-white" role="none">
                    {{ request.user.name }} {{ request.user.surname }}
                  </p>
                  <p class="text-sm font-medium text-gray-900 truncate dark:text-gray-300" role="none">
                    {{ request.user }}
                  </p>
                </div>
                <ul class="py-1" role="none">
                  <li>
                    <a href="{% url 'panel:home' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Home</a>
                  </li>
                  <li>
                    <a href="" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Settings (In progress)</a>
                  </li>
                  <li>
                    <a href="{% url "account:logout" %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Çıkış yap</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
      </div>
    </div>
  </nav>

src/panel/templates/panel/partials/_scripts.html
{% load static %}

<!-- SCRIPTS -->

<script async defer src="https://buttons.github.io/buttons.js"></script>
<script type="module" src="{% static 'panel/js/index.js' %}"></script>
<script src="{% static 'panel/js/flowbite.min.js' %}"></script>
<script src="{% static 'panel/js/datepicker.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>

src/panel/templates/panel/partials/_stylesheet.html
{% load static %}

<!-- CSS -->

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'panel/flowbite.min.css' %}">

<!-- PRECEDENCE REQ -->
<link rel="stylesheet" href="{% static 'panel/output.css' %}">