src/gts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("account.urls")),
    path('', include("panel.urls")),
]

src/panel/urls.py
from django.urls import path
from django.conf.urls import handler404, handler403

from . import views

app_name = "panel"

urlpatterns = [
    path('', views.panel_home_view, name='home'),
    path('theses/all/', views.panel_home_view, name='all_theses'),
    path('theses/my/', views.panel_my_theses_view, name='my_theses'),
    path('theses/<int:thesis_id>', views.panel_thesis_detail_view, name="thesis_detail"),
    path('theses/new/', views.panel_new_thesis_view, name="new_thesis"),
    path('theses/<int:thesis_id>/edit/', views.panel_edit_thesis_view, name="edit_thesis"),
    
    path('universities/all/', views.panel_all_universities_view, name='all_universities'),
    path('universities/<int:university_id>', views.panel_university_detail_view, name='university_detail'),
    path('universities/new/', views.panel_new_university_view, name='new_university'),
    path('universities/<int:university_id>/edit/', views.panel_edit_university_view, name='edit_university'),
    
    path('institutes/all/', views.panel_all_institutes_view, name='all_institutes'),
    path('institutes/<int:institute_id>', views.panel_institute_detail_view, name='institute_detail'),
    path('institutes/new/', views.panel_new_institute_view, name='new_institute'),
    path('institutes/<int:institute_id>/edit/', views.panel_edit_institute_view, name='edit_institute'),
    
    
    #path('types/all/', views.panel_all_types_view, name='all_types'),
    #path('types/<int:type_id>', views.panel_type_detail_view, name='type_detail'),
    #path('types/new/', views.panel_new_type_view, name='new_type'),
    #path('types/<int:type_id>/edit/', views.panel_edit_type_view, name='edit_type'),
    
    path('languages/all/', views.panel_all_languages_view, name='all_languages'),
    path('languages/<int:language_id>', views.panel_language_detail_view, name='language_detail'),
    path('languages/new/', views.panel_new_language_view, name='new_language'),
    path('languages/<int:language_id>/edit/', views.panel_edit_language_view, name='edit_language'),

]

handler404 = views.panel_404_view

src/panel/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList

from .models import Thesis, Type, Language, Institute, Subject, Keyword, University

from account.models import User

class NewThesisForm(forms.ModelForm):

    class Meta:
        model = Thesis
        fields = ['title', 'abstract', 'type', 'language', 'institute', 'subjects', 'write_date', 'page_no']

    author = User
    title = forms.CharField(max_length=500, widget=forms.TextInput(attrs={'id': 'title', 'required': True, 'placeholder': 'Thesis Title', 'class': "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"}))
    abstract = forms.CharField(max_length=5000, widget=forms.Textarea(attrs={'id': 'abstract', 'required': True, 'rows':'8', 'placeholder': 'Thesis Abstract', 'class': "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"}))
    type = forms.ModelChoiceField(queryset=Type.objects.all().order_by("name"), empty_label=None, widget=forms.Select(attrs={'name':"type", 'id':"type", 'class': "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 disabled:opacity-70 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"}))
    language = forms.ModelChoiceField(queryset=Language.objects.all().order_by("name"), empty_label=None, widget=forms.Select(attrs={'name':"language", 'id':"language", 'class': "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 disabled:opacity-70 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"}))
    institute = forms.ModelChoiceField(queryset=Institute.objects.all().order_by("university__name"), empty_label=None, widget=forms.Select(attrs={'name':"institute", 'id':"institute", 'class': "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 disabled:opacity-70 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"}))
    subjects = forms.ModelMultipleChoiceField(queryset=Subject.objects.all().order_by("heading"), widget=forms.SelectMultiple(attrs={'name':"subjects", 'id':"subjects", 'class': "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 disabled:opacity-70 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"}))
    write_date = forms.DateField(localize=False, input_formats=['%d/%m/%Y'], widget=forms.DateInput(format="%d/%m/%Y", attrs={'id': 'write_date', 'required': True, 'datepicker': True, 'placeholder': 'Please select a date.','datepicker-format':'dd/mm/yyyy', 'class': "rounded-none rounded-r-lg bg-gray-50 border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"}))
    page_no = forms.IntegerField(widget=forms.NumberInput(attrs={'id': 'page', 'required': True, 'placeholder': 'Page Count', 'class': "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 disabled:opacity-70 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"}))
    

class NewInstituteForm(forms.ModelForm):
    
    class Meta:
        model = Institute
        fields = ['name', 'university']
    
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'id': 'name', 'required': True, 'placeholder': 'Institute Name', 'class': "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 disabled:opacity-70 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"}))
    university = forms.ModelChoiceField(queryset=University.objects.all().order_by("name"), empty_label=None, widget=forms.Select(attrs={'name':"university", 'id':"university", 'class': "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 disabled:opacity-70 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"}))
    

src/panel/views.py
import datetime

from django.shortcuts import render, redirect

from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.db.models import Q, Value, F, CharField
from django.db.models.functions import Concat

from account.decorators import allowed_users
from account.models import User

from .models import Thesis, Keyword, Subject, Institute, University, Type, Language

from .forms import NewThesisForm, NewInstituteForm

from .utils import numbering


@login_required(login_url='account:login')
def panel_my_theses_view(request):

    total = 0
    page = 1
    search = None
    write = False
    supervise = False
    cosupervise = False
    query:Q = Q()

    if request.method == 'POST':
        print(request.POST)
        
        if request.POST.get('page'):
            page = int(request.POST.get('page'))
        
        if request.POST.get('search-kwd'):
            search = request.POST.get('search-kwd')
        
        if not request.POST.get('write') and not request.POST.get('supervise') and not request.POST.get('cosupervise'):
            write = True
        
        if request.POST.get('write'):
            write = True
            query = query | Q(author=request.user)
            
        if request.POST.get('supervise'):
            supervise = True
            query = query | Q(supervisor=request.user)
        
        if request.POST.get('cosupervise'):
            cosupervise = True
            query = query | Q(cosupervisor=request.user)
        
        if search:
            print(Thesis.objects.annotate(combined=Concat('title', Value(' '), 'abstract', Value(' '), 'institute__name', Value(' '), 'institute__university__name', output_field=CharField())).filter(Q(author=request.user) & (Q(combined__icontains=search) & query)).order_by('id').query)
            all_theses = Thesis.objects.annotate(combined=Concat('title', Value(' '), 'abstract', Value(' '), 'institute__name', Value(' '), 'institute__university__name', output_field=CharField())).filter(Q(author=request.user) & (Q(combined__icontains=search) & query)).order_by('id')
        else:
            all_theses = Thesis.objects.all().filter(Q(author=request.user) & query).order_by('id')
    else:
        all_theses = Thesis.objects.all().filter(author=request.user).order_by('id')
 

    total = len(all_theses)
    if total > 10:
        all_theses = numbering.paginate(all_theses, page)
    
    context = {
        'all_theses': all_theses,
        'write': write,
        'supervise': supervise,
        'cosupervise': cosupervise,
        'total': total,
        'first': ((page-1)*10)+1,
        'last': ((page-1)*10)+len(all_theses),
        'if_first': ((page-1)*10)+1 == 1,
        'if_last': ((page-1)*10)+len(all_theses) == total,
        'search': search,
        'page': page
    }

    return render(request, "panel/pages/theses/my_theses.html", context)

@login_required(login_url='account:login')
def panel_thesis_detail_view(request, thesis_id):
    try:
        thesis = Thesis.objects.get(id=thesis_id)
    except Thesis.DoesNotExist:
        return redirect("panel:all_theses")
    
    
    if request.method == 'POST':
        if request.POST.get('field') == 'delete':
            thesis.delete()
            return redirect("panel:all_theses")
            
    
    

    context = {
        'thesis': thesis,
        'subjects': ", ".join(map(str, [x.heading for x in thesis.subjects.all()])),
        'keywords': ", ".join(map(str, [x.description for x in thesis.keywords.all()])),
    }

    return render(request, "panel/pages/theses/thesis_detail.html", context)

@login_required(login_url='account:login')
def panel_new_thesis_view(request):
    
    current_user:User = request.user

    if request.method == 'POST':
        print(request.POST)
        form = NewThesisForm(data = request.POST)
        if form.is_valid():
            
            thesis:Thesis = form.save(commit=False)
            
            error:bool = False
            
            try:
                thesis.supervisor = User.objects.get(username=request.POST.get('supervisor'))
            except User.DoesNotExist:
                messages.error(request, "Supervisor couldn't be found.", extra_tags="supervisor")
                error = True
            
            if request.POST.get('cosupervisor'):
                try:
                    thesis.cosupervisor = User.objects.get(username=request.POST.get('cosupervisor'))
                except User.DoesNotExist:
                    messages.error(request, "Cosupervisor couldn't be found.", extra_tags="cosupervisor")
                    error = True
            if error:
                return redirect('panel:new_thesis')
            
            thesis.author = current_user
            thesis.save()
            
            thesis.subjects.add(*[Subject.objects.get(id=s) for s in request.POST.getlist('subjects')])
            
            kwd = request.POST.get('keywords')
            
            if kwd:
                for x in list(map(str.strip, kwd.strip('][').replace('"', '').split(','))):
                    x=x.lower()
                    if Keyword.objects.filter(description=x).exists():
                        thesis.keywords.add(Keyword.objects.get(description=x))
                    else:
                        thesis.keywords.create(description=x)
                    
            
            
            return redirect('panel:thesis_detail', thesis_id=thesis.id)
        else:
            print(form.errors)
    else:
        form = NewThesisForm()
    
    context = { 'new_thesis_form': form,
               'now': str(datetime.datetime.now()),}

    return render(request, "panel/pages/theses/new_thesis.html", context)

@login_required(login_url='account:login')
def panel_edit_thesis_view(request, thesis_id):
    
    current_user:User = request.user
    
    try:
        thesis = Thesis.objects.get(pk=thesis_id)
    except Thesis.DoesNotExist:
        return redirect("panel:all_theses")

    if request.method == 'POST':
        
        
        if request.POST.get('field') == 'delete':
            thesis.delete()
            return redirect("panel:all_theses")
        
        form = NewThesisForm(data = request.POST)
        if form.is_valid():
            form.instance.sub_date = thesis.sub_date
            thesis:Thesis = form.save(commit=False)
            thesis.id = thesis_id
            
            error:bool = False
            
            try:
                thesis.supervisor = User.objects.get(username=request.POST.get('supervisor'))
            except User.DoesNotExist:
                messages.error(request, "Supervisor couldn't be found.", extra_tags="supervisorerror")
                error = True
            
            if request.POST.get('cosupervisor'):
                try:
                    thesis.cosupervisor = User.objects.get(username=request.POST.get('cosupervisor'))
                except User.DoesNotExist:
                    messages.error(request, "Cosupervisor couldn't be found.", extra_tags="cosupervisor")
                    error = True
            else:
                thesis.cosupervisor = None
            
            
            if error:
                return redirect('panel:edit_thesis', thesis_id=thesis_id)
            
            thesis.author = current_user
            thesis.save()
            
            thesis.subjects.clear()
            thesis.subjects.add(*[Subject.objects.get(id=s) for s in request.POST.getlist('subjects')])
            
            thesis.keywords.clear()
            kwd = request.POST.get('keywords')
            
            if kwd:
                for x in list(map(str.strip, kwd.strip('][').replace('"', '').split(','))):
                    x=x.lower()
                    if Keyword.objects.filter(description=x).exists():
                        thesis.keywords.add(Keyword.objects.get(description=x))
                    else:
                        thesis.keywords.create(description=x)
                    
            
            
            return redirect('panel:thesis_detail', thesis_id=thesis.id)
    else:
        form = NewThesisForm(instance=thesis)
        
    
    keywords = ", ".join(map(str, [x.description for x in thesis.keywords.all()]))
    
    context = { 'new_thesis_form': form,
               'supervisor': thesis.supervisor.username,
               'cosupervisor': thesis.cosupervisor.username if thesis.cosupervisor else '',
               'keywords': keywords,
               'thesis_id': thesis_id,}

    return render(request, "panel/pages/theses/edit_thesis.html", context)




@login_required(login_url='account:login')
def panel_all_institutes_view(request):

    total = 0
    page = 1
    search = None

    if request.method == 'POST':
        
        if request.POST.get('page'):
            page = int(request.POST.get('page'))
        
        if request.POST.get('search-kwd'):
            search = request.POST.get('search-kwd')
    
    if search:
        all_institutes = Institute.objects.annotate(combined=Concat('name', Value(' '), 'university__name')).filter(combined__icontains=search).order_by('name')
    else:
        all_institutes = Institute.objects.all().order_by('name')
 

    total = len(all_institutes)
    if total > 10:
        all_institutes = numbering.paginate(all_institutes, page)
    
    context = {
        'all_insts': all_institutes,
        'total': total,
        'first': ((page-1)*10)+1,
        'last': ((page-1)*10)+len(all_institutes),
        'if_first': ((page-1)*10)+1 == 1,
        'if_last': ((page-1)*10)+len(all_institutes) == total,
        'search': search,
        'page': page
    }

    return render(request, "panel/pages/institutes/all_institutes.html", context)

@login_required(login_url='account:login')
def panel_institute_detail_view(request, institute_id):
    try:

src/panel/templates/panel/pages/universities/university_detail.html
{% extends "panel/partials/_base.html" %}

{% load static %}

{% load comma %}

{% block title %}GTS - University Detail{% endblock %}

{% block content %}

<div class=" px-4 pt-6 dark:bg-gray-900">
    <div class="mb-4 xl:mb-2">
        <nav class="flex mb-5" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 text-sm font-medium md:space-x-2">
              <li class="inline-flex items-center">
                <a href="{% url 'panel:home' %}" class="inline-flex items-center text-gray-700 hover:text-primary-600 dark:text-gray-300 dark:hover:text-primary-500">
                  <svg class="w-5 h-5 mr-2.5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path></svg>
                  Home
                </a>
              </li>
              <li>
                <div class="flex items-center">
                  <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                  <a href="{% url 'panel:all_universities' %}" class="ml-1 text-gray-700 hover:text-primary-600 md:ml-2 dark:text-gray-300 dark:hover:text-primary-500">Universities</a>
                </div>
              </li>
              <li>
                <div class="flex items-center">
                  <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                  <span class="ml-1 text-gray-400 md:ml-2 dark:text-gray-500" aria-current="page">
                    
                    University: #{{ university.id }}

                    </span>
                </div>
              </li>
            </ol>
        </nav>
        <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white mb-4">University Details</h1>
    </div>

    <div class="p-4 mb-4 space-y-6 bg-white border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 sm:p-6 dark:bg-gray-800">
    
        <form action="" method="POST" class="space-y-8">
            
            {% csrf_token %}

            <div class="grid grid-cols-6 gap-6 mt-4">
                {% comment %} 
                <div class="col-span-1 sm:col-span-1">
                    <img class="mb-4 rounded-lg w-28 h-28 sm:mb-0 xl:mb-4 2xl:mb-0" src="{% static 'panel/img/default_pp.png' %}" alt="">
                </div>
                <div class="col-span-5 sm:col-span-5 text-sm font-normal text-gray-500 dark:text-gray-400">
                    <div class="flex items-center">
                        <div class="h-2.5 w-2.5 rounded-full bg-gray-700 dark:bg-gray-500 mr-2"></div>
                        <div class="text-base font-semibold text-gray-900 dark:text-white">{{ thesis.author.name }} {{ thesis.author.surname }}</div>
                    </div>
                    <div class="text-sm font-normal text-gray-500 dark:text-gray-400">{{ thesis.author.username }}</div>
                </div> {% endcomment %}

                <div class="col-span-6">
                    <label for="title" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name:</label>
                    <input disabled type="text" name="name" value="{{ university.name }}" id="name" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                </div>
                <div class="col-span-6 sm:col-span-3">
                    <button type="button" class="mt-8 w-1/2 text-sm font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 sm:w-auto dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                        <a class="px-3 py-2 inline-flex items-center justify-center" href="{% url "panel:edit_university" university.id %}">
                            <svg class="w-5 h-5 mr-2 -ml-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd"></path>
                            </svg>
                            Edit University
                        </a>
                    </button>
                    <button type="button" data-modal-target="delete-university-modal" data-modal-toggle="delete-university-modal" class="inline-flex items-center justify-center mt-8 w-1/2 px-3 py-2 text-sm font-medium text-center text-white rounded-lg bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-primary-300 sm:w-auto dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-primary-800">
                        <svg class="w-4 h-4 mt-1 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                        </svg>
                        Delete University
                    </button>
                </div>
            </div>
            
        </form>
    </div>
</div>

<!-- Delete User Modal -->
<div class="fixed left-0 right-0 z-50 items-center justify-center hidden overflow-x-hidden overflow-y-auto top-4 md:inset-0 h-modal sm:h-full" id="delete-university-modal">
    <div class="relative w-full h-full max-w-md px-4 md:h-auto">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-800">
            <!-- Modal header -->
            <div class="flex justify-end p-2">
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-700 dark:hover:text-white" data-modal-toggle="delete-university-modal">
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>  
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-6 pt-0 text-center">
                <form action="" method="POST">
                    {% csrf_token %}
                    <svg class="w-16 h-16 mx-auto text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                    <h3 class="mt-5 mb-6 text-lg text-gray-500 dark:text-gray-400">Are you sure you want to delete this university? Don't forget that some theses may get affected.</h3>
                    <button type="submit" name="field" value="delete" class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-base inline-flex items-center px-3 py-2.5 text-center mr-2 dark:focus:ring-red-800">
                        Yes, delete it.
                    </button>
                    <a href="" class="text-gray-900 bg-white hover:bg-gray-100 focus:ring-4 focus:ring-primary-300 border border-gray-200 font-medium inline-flex items-center rounded-lg text-base px-3 py-2.5 text-center dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-gray-700" data-modal-toggle="delete-university-modal">
                        No, cancel it.
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}